# frozen_string_literal: true

source 'https://rubygems.org'

# gem "rails"

gem 'rspec', '~> 3.11'

gem 'tty-font', '~> 0.5.0'

gem 'tty-prompt', '~> 0.23.1'

gem 'require_all', '~> 3.0'

gem 'rainbow', '~> 3.1'
